name: "Building And Testing"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Server
        uses: actions/checkout@v4
        with:
          path: nevergarden/blastween
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install Lix
        working-directory: nevergarden/blastween
        run: |
          npm install -g lix
          npm install
          ./node_modules/.bin/haxe build.hxml
          ./node_modules/.bin/neko out/tests.n
      - name: Cache Lix Packages
        uses: actions/cache@v3
        with:
          key: lix-key-1
          path: |
            ~/haxe
            ./node_modules
